open Algebra

let db = new_database ()

let _ =
  add_table db "ActionLog"
    [ Col "logId"
    ; Col "contactId"
    ; Col "paperId"
    ; Col "time"
    ; Col "ipaddr"
    ; Col "action"
    ];

  add_table db "Capability"
    [ Col "capabilityType"
    ; Col "contactId"
    ; Col "paperId"
    ; Col "timeExpires"
    ; Col "salt"
    ; Col "data"
    ];

  add_table db "ContactInfo"
    [ Col "contactId"
    ; Col "firstName"
    ; Col "lastName"
    ; Col "unaccentedName"
    ; Col "email"
    ; Col "preferredEmail"
    ; Col "affiliation"
    ; Col "voicePhoneNumber"
    ; Col "country"
    ; Col "password"
    ; Col "passwordTime"
    ; Col "passwordUseTime"
    ; Col "collaborators"
    ; Col "creationTime"
    ; Col "updateTime"
    ; Col "lastLogin"
    ; Col "defaultWatch"
    ; Col "roles"
    ; Col "disabled"
    ; Col "contactTags"
    ; Col "data"
    ];

  add_table db "FilteredDocument"
    [ Col "inDocId"
    ; Col "filterType"
    ; Col "outDocId"
    ; Col "createdAt"
    ];

  add_table db "Formula"
    [ Col "formulaId"
    ; Col "name"
    ; Col "heading"
    ; Col "headingTitle"
    ; Col "expression"
    ; Col "createdBy"
    ; Col "timeModified"
    ];

  add_table db "MailLog"
    [ Col "mailId"
    ; Col "recipients"
    ; Col "q"
    ; Col "t"
    ; Col "paperIds"
    ; Col "cc"
    ; Col "replyto"
    ; Col "subject"
    ; Col "emailBody"
    ; Col "fromNonChair"
    ];

  add_table db "Mimetype"
    [ Col "mimetypeid"
    ; Col "mimetype"
    ; Col "extension"
    ; Col "description"
    ; Col "inline"
    ];

  add_table db "Paper"
    [ Col "paperId"
    ; Col "title"
    ; Col "authorInformation"
    ; Col "abstract"
    ; Col "collaborators"
    ; Col "timeSubmitted"
    ; Col "timeWithdrawn"
    ; Col "timeFinalSubmitted"
    ; Col "timeModified"
    ; Col "paperStorageId"
    ; Col "sha1"
    ; Col "finalPaperStorageId"
    ; Col "blind"
    ; Col "outcome"
    ; Col "leadContactId"
    ; Col "shepherdContactId"
    ; Col "managerContactId"
    ; Col "capVersion"
    ; Col "size"
    ; Col "mimetype"
    ; Col "timestamp"
    ; Col "pdfFormatStatus"
    ; Col "withdrawReason"
    ; Col "paperFormat"
    ];

  add_table db "PaperComment"
    [ Col "paperId"
    ; Col "commentId"
    ; Col "contactId"
    ; Col "timeModified"
    ; Col "timeNotified"
    ; Col "timeDisplayed"
    ; Col "comment"
    ; Col "commentType"
    ; Col "replyTo"
    ; Col "paperStorageId"
    ; Col "ordinal"
    ; Col "authorOrdinal"
    ; Col "commentTags"
    ; Col "commentRound"
    ; Col "commentFormat"
    ; Col "commentOverflow"
    ];

  add_table db "PaperConflict"
    [ Col "paperId"
    ; Col "contactId"
    ; Col "conflictType"
    ];

  add_table db "PaperOption"
    [ Col "paperId"
    ; Col "optionId"
    ; Col "value"
    ; Col "data"
    ];

  add_table db "PaperReview"
    [ Col "paperId"
    ; Col "reviewId"
    ; Col "contactId"
    ; Col "reviewToken"
    ; Col "reviewType"
    ; Col "reviewRound"
    ; Col "requestedBy"
    ; Col "timeRequested"
    ; Col "timeRequestNotified"
    ; Col "reviewBlind"
    ; Col "reviewModified"
    ; Col "reviewAuthorModified"
    ; Col "reviewSubmitted"
    ; Col "reviewNotified"
    ; Col "reviewAuthorNotified"
    ; Col "reviewAuthorSeen"
    ; Col "reviewOrdinal"
    ; Col "timeDisplayed"
    ; Col "timeApprovalRequested"
    ; Col "reviewEditVersion"
    ; Col "reviewNeedsSubmit"
    ; Col "overAllMerit"
    ; Col "reviewerQualification"
    ; Col "novelty"
    ; Col "technicalMerit"
    ; Col "interestToCommunity"
    ; Col "longevity"
    ; Col "grammar"
    ; Col "likelyPresentation"
    ; Col "suitableForShort"
    ; Col "paperSummary"
    ; Col "commentsToAuthor"
    ; Col "commentsToPC"
    ; Col "commentsToAddress"
    ; Col "weaknessOfPaper"
    ; Col "strengthOfPaper"
    ; Col "potential"
    ; Col "fixability"
    ; Col "textField7"
    ; Col "textField8"
    ; Col "reviewWordCount"
    ; Col "reviewFormat"
    ];

  add_table db "PaperReviewPreference"
    [ Col "paperId"
    ; Col "contactId"
    ; Col "preference"
    ; Col "expertise"
    ];

  add_table db "PaperReviewRefused"
    [ Col "paperId"
    ; Col "contactId"
    ; Col "requestedBy"
    ; Col "reason"
    ];

  add_table db "PaperStorage"
    [ Col "paperId"
    ; Col "paperStorageId"
    ; Col "timestamp"
    ; Col "mimetype"
    ; Col "mimetypeid"
    ; Col "paper"
    ; Col "compression"
    ; Col "sha1"
    ; Col "documentType"
    ; Col "filename"
    ; Col "infoJson"
    ; Col "size"
    ; Col "filterType"
    ; Col "originalStorageId"
    ];

  add_table db "PaperTag"
    [ Col "paperId"
    ; Col "tag"
    ; Col "tagIndex"
    ];

  add_table db "PaperTagAnno"
    [ Col "tag"
    ; Col "annoId"
    ; Col "tagIndex"
    ; Col "heading"
    ; Col "annoFormat"
    ; Col "infoJson"
    ];

  add_table db "PaperTopic"
    [ Col "paperId"
    ; Col "topicId"
    ];

  add_table db "PaperWatch"
    [ Col "paperId"
    ; Col "contactId"
    ; Col "watch"
    ];

  add_table db "ReviewRating"
    [ Col "paperId"
    ; Col "reviewId"
    ; Col "contactId"
    ; Col "rating"
    ];

  add_table db "ReviewRequest"
    [ Col "paperId"
    ; Col "name"
    ; Col "email"
    ; Col "reason"
    ; Col "requestedBy"
    ; Col "reviewRound"
    ];

  add_table db "Settings"
    [ Col "name"
    ; Col "value"
    ; Col "data"
    ];

  add_table db "TopicArea"
    [ Col "topicId"
    ; Col "topicName"
    ];

  add_table db "TopicInterest"
    [ Col "contactId"
    ; Col "topicId"
    ; Col "interest"
    ];
